### ISSUE TITLE
Can not find your contact info

### ISSUE THREAD

**Issue by EmPablo** [rambip/web-3d#1]
Hey Antonin, can not find your contact info, so I can only write something here, I see you are good with Rust, Are you willing to come and join us with a project which almost reach 9K star on GitHub, If you do we can build something amazing together. let me know, Thanks!

**Comment by rambip** [comment]
I know, I didn't create an official email for my projects yet.
I will have to do it at one point ...

Otherwise, I'm curious about your project, what is it ?
And does it have something to do with 3d stuff, typescript, webassembly, or none of those ?
(I do know a lot of different technologies, but I'm not great at rust)
Where can we continue this conversation ?
I have a [matrix](matrix.org) account if you want

**Comment by EmPablo** [comment]
@rambip We are doing this: https://github.com/rustdesk/rustdesk  and I invite you to join us together, wish we can build something amazing together.

**Comment by EmPablo** [comment]
my email: pablo@rustdesk.com
